- frontend/components/template/propertyPage/PropertyPage.tsx
- frontend/utlis/getPropertyValue.tsx
・modify/propertyDetailにpushしようとして間違えました、、
・メインタイトル追加に伴う詳細画面の修正
・入居可能日の表示を分かりやすく
> <詳細画面>メインタイトル追加に伴う変更と入居可能日をより分かりやすく表示

- frontend/components/template/propertyPage/PropertyPage.tsx
- frontend/components/template/propertyPage/SectionContents.tsx
・詳細画面デザイン微調整
・入居可能や退去日などの文字が長かったので空文字にreplace
・fixedのお問い合わせのz-indexを最大に
・アイコン変更
> 詳細画面デザイン微調整

- frontend/components/organisms/Header.tsx
- frontend/config/headerOptions.ts
> 外部リンクは別タブで開く設定

- frontend/app/(main)/chinese/error.tsx
- frontend/app/(main)/chinese/page.tsx
- frontend/app/(main)/english/error.tsx
- frontend/app/(main)/english/page.tsx
- frontend/components/organisms/Header.tsx
- frontend/config/headerOptions.ts
> 他言語ページのルーティングを追加

- frontend/components/template/propertyPage/PropertyPage.tsx
> ヘッダーのアイコンサイズ変更に伴うデザイン調整

- frontend/components/organisms/Header.tsx
- frontend/config/headerOptions.ts
- frontend/constants/links.tsx
- 留学生向け、オーナー向けのページはインスタ遷移に変更
- 他言語選択を非表示
- 会社紹介ページを非表示
> 未開発のページはインスタ遷移または非表示に変更

- frontend/components/organisms/Header.tsx
- frontend/config/headerOptions.ts
- frontend/constants/links.tsx
>  未開発のページはインスタ遷移または非表示に変更

- frontend/components/organisms/propertyDetail/PropertyDetailHeader.tsx
- frontend/components/template/propertyDetail/PropertyDetail.tsx
> 物件詳細画面用のヘッダー実装

- frontend/components/organisms/propertyDetail/PropertyDetailHeader.tsx
・スタッフコメントをスタッフからのコメントへ修正
・ヘッダーが見えていない時にもshadowが適用されていたので修正
> ヘッダー要素名とshadowの修正

- frontend/components/atoms/common/MapNotFound.tsx
- frontend/components/atoms/propertyDetail/SectionContents.tsx
- frontend/components/template/propertyDetail/_components/GoogleMapMarker.tsx
- frontend/constants/links.tsx
> 物件詳細画面の地図を非表示＆インスタのサービスガイド変更に伴う修正

- frontend/components/feature/property/PropertyDetail.tsx
- frontend/components/feature/property/PropertyList.tsx
- frontend/utlis/getPropertyValue.tsx
> 入居可能日がnullの表示

- frontend/components/common/ReadMore.tsx
（変更前）行数で指定して◯行以上文章があれば、もっと読むボタンを出す 
　-> 全文表示されていないのにもっと読むのボタンが現れない不具合あり
（変更後）指定した高さを超えた場合にトリガーを変更
> ReadMoreコンポーネント修正

- frontend/app/(main)/agencies/error.tsx
- frontend/app/(main)/agencies/page.tsx
- frontend/app/(main)/blogs/error.tsx
- frontend/app/(main)/blogs/page.tsx
- frontend/app/(main)/clinics/error.tsx
- frontend/app/(main)/clinics/page.tsx
- frontend/app/(main)/events/error.tsx
- frontend/app/(main)/events/page.tsx
- frontend/app/(main)/insurance/error.tsx
- frontend/app/(main)/insurance/page.tsx
- frontend/app/(main)/jobs/error.tsx
- frontend/app/(main)/jobs/page.tsx
- frontend/app/(main)/local-shops/error.tsx
- frontend/app/(main)/local-shops/page.tsx
- frontend/app/(main)/marketplace/error.tsx
- frontend/app/(main)/marketplace/page.tsx
- frontend/app/(main)/mobile-carriers/error.tsx
- frontend/app/(main)/mobile-carriers/page.tsx
- frontend/app/(main)/skill-market/error.tsx
- frontend/app/(main)/skill-market/page.tsx
- frontend/app/(main)/tourist-spots/error.tsx
- frontend/app/(main)/tourist-spots/page.tsx
- frontend/app/(main)/washrooms/error.tsx
- frontend/app/(main)/washrooms/page.tsx
- frontend/components/common/Categories.tsx
- frontend/components/features/property/PropertyDetail.tsx
- frontend/components/features/property/PropertyDetailContents.tsx
- frontend/components/features/property/PropertyList.tsx
> カテゴリーヘッダーにアイテムを追加、その他依頼のあった修正対応

- frontend/app/(main)/agencies/page.tsx
- frontend/app/(main)/blogs/page.tsx
- frontend/app/(main)/clinics/page.tsx
- frontend/app/(main)/events/page.tsx
- frontend/app/(main)/insurance/page.tsx
- frontend/app/(main)/jobs/page.tsx
- frontend/app/(main)/layout.tsx
- frontend/app/(main)/local-shops/page.tsx
- frontend/app/(main)/marketplace/page.tsx
- frontend/app/(main)/mobile-carriers/page.tsx
- frontend/app/(main)/skill-market/page.tsx
- frontend/app/(main)/tourist-spots/page.tsx
- frontend/app/(main)/washrooms/page.tsx
- frontend/components/common/Categories.tsx
- frontend/components/common/frame/ListPageFrame.tsx
> カテゴリーヘッダーのスクロール調整

- frontend/app/(main)/internship/error.tsx
- frontend/app/(main)/internship/page.tsx
- frontend/app/layout.tsx
- frontend/components/common/Categories.tsx
- frontend/components/common/PaginationList.tsx
- frontend/components/common/ReadMore.tsx
- frontend/components/common/Tab.tsx
- frontend/components/common/frame/DetailPageFrame.tsx
- frontend/components/common/header/Header.tsx
- frontend/components/features/property/FilterDialog.tsx
- frontend/components/features/property/PropertyDetail.tsx
- frontend/components/features/property/PropertyDetailContents.tsx
- frontend/components/ui/calendar.tsx
- frontend/tailwind.config.ts
> タイトル変更、その他いろいろ微調整

- frontend/app/(main)/layout.tsx
- frontend/app/(main)/properties/[propertyId]/page.tsx
- frontend/app/not-found.tsx
- frontend/components/common/Categories.tsx
- frontend/components/common/footer/Footer.tsx
- frontend/components/common/footer/index.tsx
- frontend/components/common/frame/DetailPageFrame.tsx
- frontend/components/common/frame/ListPageFrame.tsx
- frontend/components/common/header/Header.tsx
- frontend/components/common/loading/ListPageSkeleton.tsx
- frontend/components/common/loading/Loader.tsx
- frontend/components/common/loading/index.tsx
- frontend/components/features/property/PropertyDetail.tsx
- frontend/package-lock.json
- frontend/package.json
> フッダー作成と細かい修正

- frontend/app/not-found.tsx
- frontend/components/features/property/PropertyDetailContents.tsx
> 検証環境で見つけた細かいデザインずれの調整

- frontend/components/common/Categories.tsx
> カテゴリmargin微調整

- frontend/components/common/Categories.tsx
- frontend/components/ui/select.tsx
- frontend/tailwind.config.ts
> カテゴリヘッダ調整、コンポーネントのring回避

- strapi/.env.example
- strapi/config/middlewares.ts
- strapi/config/plugins.ts
- strapi/package-lock.json
- strapi/package.json
- strapi/src/api/author/content-types/author/schema.json
- strapi/src/api/blog/content-types/blog/schema.json
- strapi/src/api/blog/controllers/blog.ts
- strapi/src/components/blog/blog-content.json
- strapi/types/generated/components.d.ts
- strapi/types/generated/contentTypes.d.ts
> [ブログ] Strapiコンテンツタイプ作成

- frontend/components/common/frame/DetailPageFrame.tsx
- frontend/components/common/text/MarkdownRenderer.tsx
- frontend/components/features/blog/BlogDetail.tsx
- frontend/next.config.mjs
- frontend/types/blog/blogTypes.ts
- strapi/src/api/author/content-types/author/schema.json
- strapi/src/api/blog/controllers/blog.ts
- strapi/types/generated/contentTypes.d.ts
> [ブログ] 記事を書いた人の情報追加

- frontend/app/(main)/properties/page.tsx
- [-] develop へのマージリクエストとなっているか
- [-] `npm run build`を実行しエラーは出ていないか
誤: `params: Promise<SearchParams>`
正: `searchParams: Promise<SearchParams>`
> [マージ] 動的APIはsearchParamsでないと検索が効かない

- strapi/src/api/blog/content-types/blog/schema.json
- strapi/src/components/common/article-content.json
- strapi/types/generated/components.d.ts
- strapi/types/generated/contentTypes.d.ts
- [-] `npm run build` を実行しエラーは出ていないか
- タイトルの字数制限を撤廃
> ブログ タイトルの字数制限を撤廃

- strapi/src/api/event-category/content-types/event-category/schema.json
- strapi/src/api/event-category/controllers/event-category.ts
- strapi/src/api/event-category/routes/event-category.ts
- strapi/src/api/event-category/services/event-category.ts
- strapi/src/api/event-organizer/content-types/event-organizer/schema.json
- strapi/src/api/event-organizer/controllers/event-organizer.ts
- strapi/src/api/event-organizer/routes/event-organizer.ts
- strapi/src/api/event-organizer/services/event-organizer.ts
- strapi/src/api/event/content-types/event/schema.json
- strapi/src/api/event/controllers/event.ts
- strapi/src/api/event/routes/event.ts
- strapi/src/api/event/services/event.ts
- strapi/src/components/common/faq.json
- strapi/src/components/common/image-with-description.json
- strapi/types/generated/components.d.ts
- strapi/types/generated/contentTypes.d.ts
- [-] `npm run build` を実行しエラーは出ていないか
- イベントのContent-Type Builderを作成
なし
なし
なし
> イベントのContent-Type Builderを作成
